---

- name: Update repositories cache and install packages
  apt: 
    name: "{{ item }}" 
    update_cache: yes
  with_items:
    - python
    - python-pip
    - libffi-dev
    - gcc
    - libssl-dev
  become_method: sudo
  become: yes
  become_user: root

- name: install libraries with pip
  pip: 
    name: "{{ item }}" 
    state: present
  with_items:
    - virtualenv
  become_method: sudo
  become: yes
  become_user: root

- name: Create tmp edxthemevenv
  file: 
    path: ~/.edxthemevenv 
    state: directory

- name: copy requirements to edxthemevenv
  copy: 
    src: "{{ item }}" 
    dest: "~/.edxthemevenv"
  with_items:
    - requirements_main.txt

- name: install requirements
  pip: 
    requirements: "{{ item }}" 
    virtualenv: "~/.edxthemevenv" 
    state: present
  with_items:
    - ~/.edxthemevenv/requirements_main.txt
