---
- hosts: "{{ edx_hosts | default('localhost') }}"
  roles: 
    - { role: "update-com-theme", ignore_errors: no,
        theme_dir: "/edx/app/edxapp/themes",
        theme_repo: "https://github.com/raccoongang/themes_for_themex.io.git",
        theme_branch: "racoongang-theme",
        json_path: '/edx/app/edxapp',
        server_vars_path: '/edx/app/edx_ansible/server-vars.yml',
        THEME_DIRS: "{{ theme_dir }}",
        SITE_THEME: "{{ theme_branch }}",
        COMMON_DATA_DIR: "/edx/var/",
        edxapp_data_dir: "{{ COMMON_DATA_DIR }}/edxapp",
        edxapp_staticfile_dir: "{{ edxapp_data_dir }}/staticfiles",
        edxapp_user: "edxapp",
        common_web_group: "www-data",
        git_key: "{{ lookup('file', '~/.ssh/id_rsa_git') }}"

      }
